name: CI

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install zsh
      run: sudo apt-get install -y zsh

    - name: assemble
      run: ./assemble.sh || true
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: Installomator.sh
