name: CI

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install zsh
      run: sudo apt-get install -y zsh

    - name: assemble
      run: ./assemble.sh || true

    - name: nodebug
      run: sed -e 's/^DEBUG=1$/DEBUG=0/g' ./Installomator.sh > tmpfile && mv tmpfile ./Installomator.sh

    - name: chmod
      run: chmod 755 ./Installomator.sh
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: Installomator.sh
