name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: assemble
      run: ./assemble.sh --pkg

    - name: Create a Release in a GitHub Action
      uses: comnoco/create-release-action@v2.0.5
            
